FROM python:3.9
ARG MONGODB_URL
ENV MONGODB_URL=$MONGODB_URL
COPY ./app /app

COPY requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
# CMD ["python", "app/main.py"]
CMD ["gunicorn", "-b", ":5000", "app.main:app"]