version: 2.0
jobs:
    build:
        docker:
            - image: kostnerek/montechristo
              auth:
                  username: kostnerek
                  password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
