version: 2.1
workflows:
    my-workflow:
        jobs:
            - build:
                  context:
                      - montechristo-env-vars
jobs:
    build:
        machine: true
        steps:
            - checkout
            # start proprietary DB using private Docker image
            # with credentials stored in the UI
            - run: |
                  echo "$DOCKERHUB_PASSWORD" | docker login --username kostnerek --password-stdin
                  docker run -d --name montechristo kostnerek/montechristo

            # build the application image
            - run: docker build -t kostnerek/montechristo .

            # deploy the image
            - run: docker push kostnerek/montechristo
            - run: |
                  ssh -i $OPENSSH VPSUSER@VPSIP
                  docker pull kostnerek/montechristo
                  docker stop montechristo
                  docker rm montechristo
                  docker run --name:montechristo -p 80:80 -d kostnerek/montechristo --restart=always
                  exit
