#config for be
version: 2.1
workflows:
    backend-workflow:
        jobs:
            - build:
                  context:
                      - montechristo-env-vars
                  filters:
                      branches:
                          only:
                              - dev

jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                  echo "$DOCKERHUB_PASSWORD" | docker login --username kostnerek --password-stdin

            - run: docker build --build-arg MONGODB_URL -f Dockerfile.api -t kostnerek/montechristo .

            # deploy the image
            - run: docker push kostnerek/montechristo
            - add_ssh_keys:
                  fingerprints:
                      - "04:f8:a5:21:e4:db:78:be:53:20:be:7c:d0:b3:8e:12"
            - run: |
                  ssh lema@20.222.251.245 \<<'ENDSSH'
                  sudo docker pull kostnerek/montechristo
                  sudo docker kill lema_client_1
                  sudo docker kill lema_api_1
                  tmux new -d 'sudo docker-compose -f /home/lema/docker-compose.yml up'
                  ENDSSH
